apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-db-credentials
  namespace: vik
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
  data:
  - secretKey: mongo-root-username
    remoteRef:
      key: "dev"
      property: "mongo-root-username"
  - secretKey: mongo-root-password
    remoteRef:
      key: "dev"
      property: "mongo-root-password"