spring:
  application:
    name: employee
  data:
    mongodb:
      # blah values overidden by env values defined in deployment.yaml and external /config/application.properties
      host: blah
      database: blah
      username: blah
      password: blah
  output.ansi.enabled: ALWAYS

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS